In [11]:
import pandas as pd
import csv

In [29]:
dataset = pd.read_csv('Desktop/training.1600000.processed.noemoticon.csv',quoting=csv.QUOTE_NONE,sep='delimiter',error_bad_lines=False)
dataset

/home/pulkit/anaconda3/envs/virtual_platform/lib/python3.5/site-packages/ipykernel_launcher.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  """Entry point for launching an IPython kernel.

     "0","1467810369","Mon Apr 06 22:19:45 PDT 2009","NO_QUERY","_TheSpecialOne_","@switchfoot http://twitpic.com/2y1zl - Awww, that's a bummer.  You shoulda got David Carr of Third Day to do it. ;D"
0     "0","1467810672","Mon Apr 06 22:19:49 PDT 2009...
1     "0","1467810917","Mon Apr 06 22:19:53 PDT 2009...
2     "0","1467811184","Mon Apr 06 22:19:57 PDT 2009...
3     "0","1467811193","Mon Apr 06 22:19:57 PDT 2009...
4     "0","1467811372","Mon Apr 06 22:20:00 PDT 2009...
5     "0","1467811592","Mon Apr 06 22:20:03 PDT 2009...
6     "0","1467811594","Mon Apr 06 22:20:03 PDT 2009...
7     "0","1467811795","Mon Apr 06 22:20:05 PDT 2009...
8     "0","1467812025","Mon Apr 06 22:20:09 PDT 2009...
9     "0","1467812416","Mon Apr 06 22:20:16 PDT 2009...
10    "0","1467812579","Mon Apr 06 22:20:17 PDT 2009...
11    "0","1467812723","Mon Apr 06 22:20:19 PDT 2009...
12    "0","1467812771","Mon Apr 06 22:20:19 PDT 2009...
13    "0","1467812784","Mon Apr 06 22:20:20 PDT 2009...
14    "0","1467812799","Mon Apr 06 22:20:20 PDT 2009...
15    "0","1467812964","Mon Apr 06 22:20:22 PDT 2009...
16    "0","1467813137","Mon Apr 06 22:20:25 PDT 2009...
17    "0","1467813579","Mon Apr 06 22:20:31 PDT 2009...
18    "0","1467813782","Mon Apr 06 22:20:34 PDT 2009...
19    "0","1467813985","Mon Apr 06 22:20:37 PDT 2009...
20    "0","1467813992","Mon Apr 06 22:20:38 PDT 2009...
21    "0","1467814119","Mon Apr 06 22:20:40 PDT 2009...
22    "0","1467814180","Mon Apr 06 22:20:40 PDT 2009...
23    "0","1467814192","Mon Apr 06 22:20:41 PDT 2009...
24    "0","1467814438","Mon Apr 06 22:20:44 PDT 2009...
25    "0","1467814783","Mon Apr 06 22:20:50 PDT 2009...
26    "0","1467814883","Mon Apr 06 22:20:52 PDT 2009...
27    "0","1467815199","Mon Apr 06 22:20:56 PDT 2009...
28    "0","1467815753","Mon Apr 06 22:21:04 PDT 2009...
29    "0","1467815923","Mon Apr 06 22:21:07 PDT 2009...
...                                                 ...
6988  "0","1469639421","Tue Apr 07 06:59:02 PDT 2009...
6989  "0","1469639652","Tue Apr 07 06:59:06 PDT 2009...
6990  "0","1469639686","Tue Apr 07 06:59:05 PDT 2009...
6991  "0","1469639739","Tue Apr 07 06:59:05 PDT 2009...
6992  "0","1469640280","Tue Apr 07 06:59:11 PDT 2009...
6993  "0","1469641005","Tue Apr 07 06:59:19 PDT 2009...
6994  "0","1469641026","Tue Apr 07 06:59:18 PDT 2009...
6995  "0","1469641037","Tue Apr 07 06:59:19 PDT 2009...
6996  "0","1469641399","Tue Apr 07 06:59:22 PDT 2009...
6997  "0","1469641674","Tue Apr 07 06:59:25 PDT 2009...
6998  "0","1469641846","Tue Apr 07 06:59:27 PDT 2009...
6999  "0","1469641928","Tue Apr 07 06:59:29 PDT 2009...
7000  "0","1469642002","Tue Apr 07 06:59:29 PDT 2009...
7001  "0","1469642052","Tue Apr 07 06:59:29 PDT 2009...
7002  "0","1469642064","Tue Apr 07 06:59:31 PDT 2009...
7003  "0","1469642297","Tue Apr 07 06:59:33 PDT 2009...
7004  "0","1469642381","Tue Apr 07 06:59:33 PDT 2009...
7005  "0","1469642427","Tue Apr 07 06:59:35 PDT 2009...
7006  "0","1469642473","Tue Apr 07 06:59:34 PDT 2009...
7007  "0","1469642521","Tue Apr 07 06:59:35 PDT 2009...
7008  "0","1469642527","Tue Apr 07 06:59:35 PDT 2009...
7009  "0","1469642594","Tue Apr 07 06:59:36 PDT 2009...
7010  "0","1469642772","Tue Apr 07 06:59:39 PDT 2009...
7011  "0","1469642790","Tue Apr 07 06:59:38 PDT 2009...
7012  "0","1469643373","Tue Apr 07 06:59:45 PDT 2009...
7013  "0","1469643486","Tue Apr 07 06:59:46 PDT 2009...
7014  "0","1469644019","Tue Apr 07 06:59:52 PDT 2009...
7015  "0","1469644323","Tue Apr 07 06:59:55 PDT 2009...
7016  "0","1469644758","Tue Apr 07 07:00:01 PDT 2009...
7017  "0","1469645142","Tue Apr 07 07:00:04 PDT 2009...

[7018 rows x 1 columns]